### ISSUE TITLE
Add support for GitHub Action

### ISSUE THREAD

**Issue by tehKapa** [ptkdev/all-shields-cli#1]
### Feature description

Add support for GitHub Action so we can manage, for example, build badges like this one

[![GitHub CI](https://github.com/fastify/fastify/workflows/ci/badge.svg)](https://github.com/fastify/fastify/actions)

### Feature motivation

GitHub Actions dedicated to CI/CD pipelines are becoming a "standard" for all repositories.

**Comment by ptkdev** [comment]
Available in **v1.2.0**
